### ISSUE TITLE
Echoh  Error no subgraph in module

### ISSUE THREAD

**Issue by seang96** [fwartner/home-assistant-wakewords-collection#40]
I am using openwakeword in a container and loaded it with the --custom-model-dir set to /custom. The wake word shows in home assistant. Running a test for activation, everything fails though. I get the following error in openwakeword.

```
ERROR:root:Unexpected error in wake word thread (echoh)
Traceback (most recent call last):
  File "/usr/src/.venv/lib/python3.11/site-packages/wyoming_openwakeword/openwakeword.py", line 248, in ww_proc
    ww_model = tflite.Interpreter(model_path=str(ww_model_path), num_threads=1)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/.venv/lib/python3.11/site-packages/tflite_runtime/interpreter.py", line 464, in __init__
    self._interpreter = _interpreter_wrapper.CreateWrapperFromFile(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: No subgraph in the model.

INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
```

**Comment by fwartner** [comment]
Could you tell which model you are trying to use? Or is it a general problem? If its a general problem, i cannot take action of this since it seems to be an issue by the addon itself.

**Comment by seang96** [comment]
All of the default models work. I only tried the echoh model and received this error.

**Comment by fwartner** [comment]
Alright. Then i will (for now) delete the model. Thank your for letting me know!
