### ISSUE TITLE
[REQUEST] Please include  'Assist' as a wake word

### ISSUE THREAD

**Issue by Hedda** [fwartner/home-assistant-wakewords-collection#53]
**Is your feature request related to a problem? Please describe.**

Please consider including a wake word here that is simply 'Assist' as part of optional wakeword, or rather "Hey Assist" and "Okay Assist".

- _**Hey Assist.**_

and 

- _**Okay Assist.**_

And with "Assist" I am referring to Home Assistant's Assist for the standard Assist pipeline in Home Assistant:

* https://www.home-assistant.io/voice_control/

After all, Home Assistant's official voice assistant is called "Assistant", and there are even official logos and branding for that name.

![image](https://github.com/user-attachments/assets/4d4b4b64-8382-4142-97c9-850cd2274b3f)

**Describe the solution you'd like**

Add wakewords

- _**Hey Assist.**_

and 

- _**Okay Assist.**_

**Describe alternatives you've considered**

My reasons for the request is partially for the same as in https://github.com/esphome/micro-wake-word-models/issues/8 which are that 'Nabu' / 'Nabucasa' does not have same brand recognition. Nabu as in Nabu Casa is also only the official partner to Open Home Foundation and the ESPHome and Home Assistant projects, so it does not make much sense of it being a default.

Even on Nabu Casa's website it says that "Assist" is the official name that the voice assistant, so makes no sence "Nabu" being default?

**Additional context**

I also submitted this as a feature request here as wish it was included by default  -> https://github.com/esphome/micro-wake-word-models/issues/11

**Comment by fwartner** [comment]
Please open up a comment on https://github.com/fwartner/home-assistant-wakewords-collection/discussions/46
